{
 "title": "JMX Dashboard(Basic)",
 "description": "jmx exporter monitor",
 "tags": [
  "jmx",
  "JVM",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": { "query": "label_values(jvm_info, job)" } },
   {
    "name": "app",
    "label": "app",
    "query": {
     "query": "label_values(jvm_info,instance)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(up{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "memarea",
    "query": {
     "query": "label_values(jvm_memory_bytes_used{job=\"$job\", instance=\"$app$node\"}, area)"
    }
   },
   {
    "name": "mempool",
    "query": {
     "query": "label_values(jvm_memory_pool_bytes_max{job=\"$job\", instance=\"$app$node\"}, pool)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "JDK",
     "type": "stat",
     "gridPos": { "h": 2, "w": 22, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "label_join(jvm_info{job=\"$job\", instance=\"$app$node\"}, \"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
      }
     ]
    },
    {
     "title": "Status",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "Status"
      }
     ]
    },
    {
     "title": "State",
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 20, "x": 2, "y": 3 },
     "targets": [
      {
       "expr": "up{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "State"
      }
     ]
    },
    {
     "title": "Open File Descriptors",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 22, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "process_open_fds{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "Descriptors"
      }
     ]
    }
   ]
  },
  { "title": "Memory JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "JVM Memory Used [$memarea]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "repeat": "memarea",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=~\"$memarea\",job=\"$job\", instance=\"$app$node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_bytes_max{area=~\"$memarea\",job=\"$job\",instance=\"$app$node\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "JVM Memory Usage [$memarea]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "repeat": "memarea",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"$memarea\",job=\"$job\", instance=\"$app$node\"} / (jvm_memory_bytes_max{area=\"$memarea\", job=\"$job\",instance=\"$app$node\"} >=0) *100",
     "legendFormat": "JVM"
    }
   ]
  },
  {
   "title": "JVM Memory committed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_committed{job=\"$job\", instance=\"$app$node\"}",
     "legendFormat": "{{area}}"
    }
   ]
  },
  { "title": "Memory JVM Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Memory pool [$mempool]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "repeat": "mempool",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=~\"$mempool\",job=\"$job\",instance=\"$app$node\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=~\"$mempool\",job=\"$job\",instance=\"$app$node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=~\"$mempool\",job=\"$job\",instance=\"$app$node\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "rate(jvm_memory_pool_bytes_committed{pool=~\"$mempool\",job=\"$job\",instance=\"$app$node\"}[$__rate_interval])",
     "legendFormat": "Committed Rate"
    }
   ]
  },
  { "title": "Garbage Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "GC count increase(per 5m(",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{job=\"$job\", instance=\"$app$node\"}[5m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC count rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC Time increase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{job=\"$job\", instance=\"$app$node\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC Time rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Threading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Threading Threads",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 11, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "java_lang_Threading_ThreadCount{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "Current"
      },
      {
       "expr": "java_lang_Threading_DaemonThreadCount{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "Daemon"
      },
      {
       "expr": "java_lang_Threading_PeakThreadCount{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "Peak"
      },
      {
       "expr": "java_lang_Threading_TotalStartedThreadCount{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "Started"
      }
     ]
    },
    {
     "title": "JVM Threads current",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 11, "x": 11, "y": 21 },
     "targets": [
      {
       "expr": "jvm_threads_current{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "Current"
      },
      {
       "expr": "jvm_threads_daemon{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "Daemon"
      },
      {
       "expr": "jvm_threads_deadlocked{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "Deadlocked"
      },
      {
       "expr": "jvm_threads_deadlocked_monitor{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "Deadlocked monitor"
      },
      {
       "expr": "jvm_threads_peak{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "Peak"
      },
      {
       "expr": "jvm_threads_started_total{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "Started Total"
      }
     ]
    },
    {
     "title": "JVM Threading Threads increase",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 11, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(java_lang_Threading_ThreadCount{job=\"$job\", instance=\"$app$node\"}[$__interval])",
       "legendFormat": "Current"
      },
      {
       "expr": "increase(java_lang_Threading_DaemonThreadCount{job=\"$job\", instance=\"$app$node\"}[$__interval])",
       "legendFormat": "Daemon"
      },
      {
       "expr": "increase(java_lang_Threading_PeakThreadCount{job=\"$job\", instance=\"$app$node\"}[$__interval])",
       "legendFormat": "Peak"
      },
      {
       "expr": "increase(java_lang_Threading_TotalStartedThreadCount{job=\"$job\", instance=\"$app$node\"}[$__interval])",
       "legendFormat": "Started"
      }
     ]
    },
    {
     "title": "JVM Threads current increase",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 11, "x": 11, "y": 32 },
     "targets": [
      {
       "expr": "increase(jvm_threads_current{job=\"$job\", instance=\"$app$node\"}[$__interval])",
       "legendFormat": "Current"
      },
      {
       "expr": "increase(jvm_threads_daemon{job=\"$job\", instance=\"$app$node\"}[$__interval])",
       "legendFormat": "Daemon"
      },
      {
       "expr": "increase(jvm_threads_deadlocked{job=\"$job\", instance=\"$app$node\"}[$__interval])",
       "legendFormat": "Deadlocked"
      },
      {
       "expr": "increase(jvm_threads_deadlocked_monitor{job=\"$job\", instance=\"$app$node\"}[$__interval])",
       "legendFormat": "Deadlocked monitor"
      },
      {
       "expr": "increase(jvm_threads_peak{job=\"$job\", instance=\"$app$node\"}[$__interval])",
       "legendFormat": "Peak"
      },
      {
       "expr": "increase(jvm_threads_started_total{job=\"$job\", instance=\"$app$node\"}[$__interval])",
       "legendFormat": "Started Total"
      }
     ]
    },
    {
     "title": "JVM Threading Threads rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 11, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(java_lang_Threading_ThreadCount{job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
       "legendFormat": "Current"
      },
      {
       "expr": "rate(java_lang_Threading_DaemonThreadCount{job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
       "legendFormat": "Daemon"
      },
      {
       "expr": "rate(java_lang_Threading_PeakThreadCount{job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
       "legendFormat": "Peak"
      },
      {
       "expr": "rate(java_lang_Threading_TotalStartedThreadCount{job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
       "legendFormat": "Started"
      }
     ]
    },
    {
     "title": "JVM Threads current rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 11, "x": 11, "y": 43 },
     "targets": [
      {
       "expr": "increase(jvm_threads_current{job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
       "legendFormat": "Current"
      },
      {
       "expr": "rate(jvm_threads_daemon{job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
       "legendFormat": "Daemon"
      },
      {
       "expr": "rate(jvm_threads_deadlocked{job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
       "legendFormat": "Deadlocked"
      },
      {
       "expr": "rate(jvm_threads_deadlocked_monitor{job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
       "legendFormat": "Deadlocked monitor"
      },
      {
       "expr": "rate(jvm_threads_peak{job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
       "legendFormat": "Peak"
      },
      {
       "expr": "rate(jvm_threads_started_total{job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
       "legendFormat": "Started Total"
      }
     ]
    }
   ]
  },
  { "title": "Classes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Classes Loaded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_classes_currently_loaded {job=\"$job\", instance=\"$app$node\"}",
     "legendFormat": "currently"
    },
    {
     "expr": "jvm_classes_loaded_total{job=\"$job\", instance=\"$app$node\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Classes Loaded increase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(jvm_classes_currently_loaded {job=\"$job\", instance=\"$app$node\"}[$__interval])",
     "legendFormat": "currently"
    },
    {
     "expr": "increase(jvm_classes_loaded_total{job=\"$job\", instance=\"$app$node\"}[$__interval])",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Classes Loaded rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(jvm_classes_currently_loaded {job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
     "legendFormat": "currently"
    },
    {
     "expr": "rate(jvm_classes_loaded_total{job=\"$job\", instance=\"$app$node\"}[$__rate_interval])",
     "legendFormat": "total"
    }
   ]
  }
 ]
}