{
 "title": "JVM Exporter",
 "description": "Logstash monitoring via prometheus",
 "tags": [
  "prometheus",
  "JVM",
  "demo"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "app", "query": { "query": "label_values(jvm_info,app)" } }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Usage %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$app.+\", container!=\"\"}) by (pod) / sum(kube_pod_container_resource_limits{resource=\"memory\", pod=~\"$app.+\", container!=\"\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"$app.+\", image!=\"\", container!=\"POD\"}[5m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM Memory Used [heap]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "repeat": "memarea",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=~\"heap\",app=~\"$app\"}",
     "legendFormat": "{{pod}}-Userd"
    },
    {
     "expr": "jvm_memory_bytes_max{area=~\"heap\",app=~\"$app\"}",
     "legendFormat": "{{pod}}-Max"
    }
   ]
  },
  {
   "title": "JVM Memory Used [nonheap]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=~\"nonheap\",app=~\"$app\"}",
     "legendFormat": "{{pod}}-Used"
    },
    {
     "expr": "jvm_memory_bytes_max{area=~\"$memarea\",job=\"$job\",instance=\"$app$node\"}",
     "legendFormat": "{{pod}}-Max"
    }
   ]
  },
  {
   "title": "JVM Memory Usage [heap] Percentage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "repeat": "memarea",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",app=~\"$app\"} / (jvm_memory_bytes_max{area=\"heap\",app=~\"$app\"} >=0) *100",
     "legendFormat": "{{pod}}-JVM"
    }
   ]
  },
  {
   "title": "GC count increase(per 5m(",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{app=~\"$app\"}[5m])",
     "legendFormat": "{{pod}}-{{gc}}"
    }
   ]
  },
  {
   "title": "GC count rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{app=~\"$app\"}[$__rate_interval])",
     "legendFormat": "{{pod}}-{{gc}}"
    }
   ]
  },
  {
   "title": "GC Time increase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{app=~\"$app\"}[$__interval])",
     "legendFormat": "{{pod}}-{{gc}}"
    }
   ]
  },
  {
   "title": "GC Time rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{app=~\"$app\"}[$__rate_interval])",
     "legendFormat": "{{pod}}-{{gc}}"
    }
   ]
  }
 ]
}