{
 "title": "JMX Dashboard(Basic)",
 "description": "jmx exporter monitor",
 "tags": [
  "JVM",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "app", "label": "app", "query": { "query": "label_values(jvm_info,app)" } },
   {
    "name": "mempool",
    "query": {
     "query": "label_values(jvm_memory_pool_bytes_max{app=\"$app\"},pool)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(jvm_info{app=\"$app\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_info{app=\"$app\", pod=\"$pod\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Memory Limit",
   "type": "stat",
   "description": "Pod memory limit",
   "gridPos": { "h": 5, "w": 5, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{pod=~\"$pod\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "description": "Include cache",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod=~\"$pod\",container!=\"\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "description": "Exclude cache",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=~\"$pod\",container!=\"\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{pod=\"$pod\",app=\"$app\"}",
     "legendFormat": "Descriptors"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "timeseries",
   "description": "Exclude cache",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=\"$pod\",container!=\"\"}) by (pod) / sum(kube_pod_container_resource_limits{resource=\"memory\", pod=\"$pod\", container!=\"\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=\"$pod\", image!=\"\", container!=\"\"}[5m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Memory JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "JVM Memory Used [heap]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "repeat": "memarea",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=~\"heap\",app=\"$app\",pod=\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_bytes_max{area=~\"heap\",app=\"$app\",pod=\"$pod\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "JVM Memory Used [nonheap]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "repeat": "memarea",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=~\"nonheap\",app=\"$app\",pod=\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_bytes_max{area=~\"nonheap\",app=\"$app\",pod=\"$pod\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "JVM Memory Usage [heap]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "repeat": "memarea",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",app=\"$app\",pod=\"$pod\"} / (jvm_memory_bytes_max{area=\"heap\",app=\"$app\",pod=\"$pod\"} >=0) *100",
     "legendFormat": "JVM"
    }
   ]
  },
  {
   "title": "JVM Memory committed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_committed{app=\"$app\",pod=\"$pod\"}",
     "legendFormat": "{{area}}"
    }
   ]
  },
  { "title": "Garbage Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "GC count increase(per 5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{app=\"$app\",pod=\"$pod\"}[5m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC count rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{app=\"$app\",pod=\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC Time increase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{app=\"$app\",pod=\"$pod\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC Time rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{app=\"$app\",pod=\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Threading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Threading Threads",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "java_lang_Threading_ThreadCount{app=\"$app\",pod=\"$pod\"}",
       "legendFormat": "Current"
      },
      {
       "expr": "java_lang_Threading_DaemonThreadCount{app=\"$app\",pod=\"$pod\"}",
       "legendFormat": "Daemon"
      },
      {
       "expr": "java_lang_Threading_PeakThreadCount{app=\"$app\",pod=\"$pod\"}",
       "legendFormat": "Peak"
      },
      {
       "expr": "java_lang_Threading_TotalStartedThreadCount{app=\"$app\",pod=\"$pod\"}",
       "legendFormat": "Started"
      }
     ]
    },
    {
     "title": "JVM Threads current",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 98 },
     "targets": [
      {
       "expr": "jvm_threads_current{app=\"$app\",pod=\"$pod\"}",
       "legendFormat": "Current"
      },
      {
       "expr": "jvm_threads_daemon{job=\"$job\", instance=\"$app$node\"}",
       "legendFormat": "Daemon"
      },
      {
       "expr": "jvm_threads_deadlocked{app=\"$app\",pod=\"$pod\"}",
       "legendFormat": "Deadlocked"
      },
      {
       "expr": "jvm_threads_deadlocked_monitor{app=\"$app\",pod=\"$pod\"}",
       "legendFormat": "Deadlocked monitor"
      },
      {
       "expr": "jvm_threads_peak{app=\"$app\",pod=\"$pod\"}",
       "legendFormat": "Peak"
      },
      {
       "expr": "jvm_threads_started_total{app=\"$app\",pod=\"$pod\"}",
       "legendFormat": "Started Total"
      }
     ]
    },
    {
     "title": "JVM Threading Threads increase",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(java_lang_Threading_ThreadCount{app=\"$app\",pod=\"$pod\"}[$__interval])",
       "legendFormat": "Current"
      },
      {
       "expr": "increase(java_lang_Threading_DaemonThreadCount{app=\"$app\",pod=\"$pod\"}[$__interval])",
       "legendFormat": "Daemon"
      },
      {
       "expr": "increase(java_lang_Threading_PeakThreadCount{app=\"$app\",pod=\"$pod\"}[$__interval])",
       "legendFormat": "Peak"
      },
      {
       "expr": "increase(java_lang_Threading_TotalStartedThreadCount{app=\"$app\",pod=\"$pod\"}[$__interval])",
       "legendFormat": "Started"
      }
     ]
    },
    {
     "title": "JVM Threads current increase",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 109 },
     "targets": [
      {
       "expr": "increase(jvm_threads_current{app=\"$app\",pod=\"$pod\"}[$__interval])",
       "legendFormat": "Current"
      },
      {
       "expr": "increase(jvm_threads_daemon{app=\"$app\",pod=\"$pod\"}[$__interval])",
       "legendFormat": "Daemon"
      },
      {
       "expr": "increase(jvm_threads_deadlocked{app=\"$app\",pod=\"$pod\"}[$__interval])",
       "legendFormat": "Deadlocked"
      },
      {
       "expr": "increase(jvm_threads_deadlocked_monitor{app=\"$app\",pod=\"$pod\"}[$__interval])",
       "legendFormat": "Deadlocked monitor"
      },
      {
       "expr": "increase(jvm_threads_peak{app=\"$app\",pod=\"$pod\"}[$__interval])",
       "legendFormat": "Peak"
      },
      {
       "expr": "increase(jvm_threads_started_total{app=\"$app\",pod=\"$pod\"}[$__interval])",
       "legendFormat": "Started Total"
      }
     ]
    },
    {
     "title": "JVM Threading Threads rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(java_lang_Threading_ThreadCount{app=\"$app\",pod=\"$pod\"}[$__rate_interval])",
       "legendFormat": "Current"
      },
      {
       "expr": "rate(java_lang_Threading_DaemonThreadCount{app=\"$app\",pod=\"$pod\"}[$__rate_interval])",
       "legendFormat": "Daemon"
      },
      {
       "expr": "rate(java_lang_Threading_PeakThreadCount{app=\"$app\",pod=\"$pod\"}[$__rate_interval])",
       "legendFormat": "Peak"
      },
      {
       "expr": "rate(java_lang_Threading_TotalStartedThreadCount{app=\"$app\",pod=\"$pod\"}[$__rate_interval])",
       "legendFormat": "Started"
      }
     ]
    },
    {
     "title": "JVM Threads current rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 120 },
     "targets": [
      {
       "expr": "increase(jvm_threads_current{app=\"$app\",pod=\"$pod\"}[$__rate_interval])",
       "legendFormat": "Current"
      },
      {
       "expr": "rate(jvm_threads_daemon{app=\"$app\",pod=\"$pod\"}[$__rate_interval])",
       "legendFormat": "Daemon"
      },
      {
       "expr": "rate(jvm_threads_deadlocked{app=\"$app\",pod=\"$pod\"}[$__rate_interval])",
       "legendFormat": "Deadlocked"
      },
      {
       "expr": "rate(jvm_threads_deadlocked_monitor{app=\"$app\",pod=\"$pod\"}[$__rate_interval])",
       "legendFormat": "Deadlocked monitor"
      },
      {
       "expr": "rate(jvm_threads_peak{app=\"$app\",pod=\"$pod\"}[$__rate_interval])",
       "legendFormat": "Peak"
      },
      {
       "expr": "rate(jvm_threads_started_total{app=\"$app\",pod=\"$pod\"}[$__rate_interval])",
       "legendFormat": "Started Total"
      }
     ]
    }
   ]
  },
  { "title": "Memory JVM Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Memory pool [$mempool]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 51 },
   "repeat": "mempool",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{app=\"$app\",pod=\"$pod\",pool=~\"$mempool\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{app=\"$app\",pod=\"$pod\",pool=~\"$mempool\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{app=\"$app\",pod=\"$pod\",pool=~\"$mempool\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "rate(jvm_memory_pool_bytes_committed{app=\"$app\",pod=\"$pod\",pool=~\"$mempool\"}[$__rate_interval])",
     "legendFormat": "Committed Rate"
    }
   ]
  },
  {
   "title": "Classes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "title": "Classes Loaded",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_classes_currently_loaded {app=\"$app\",pod=\"$pod\"}",
       "legendFormat": "currently"
      },
      {
       "expr": "jvm_classes_loaded_total{app=\"$app\",pod=\"$pod\"}",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Classes Loaded increase",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(jvm_classes_currently_loaded {app=\"$app\",pod=\"$pod\"}[$__interval])",
       "legendFormat": "currently"
      },
      {
       "expr": "increase(jvm_classes_loaded_total{app=\"$app\",pod=\"$pod\"}[$__interval])",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Classes Loaded rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(jvm_classes_currently_loaded {app=\"$app\",pod=\"$pod\"}[$__rate_interval])",
       "legendFormat": "currently"
      },
      {
       "expr": "rate(jvm_classes_loaded_total{app=\"$app\",pod=\"$pod\"}[$__rate_interval])",
       "legendFormat": "total"
      }
     ]
    }
   ]
  }
 ]
}