apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: logstash
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: logstash
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Pods
    pods:
      metric:
        name: jvm_memory_bytes_heap_used
      target:
        type: AverageValue
        # max_heap_mem=518979584, 518979584*0.5=259,489,792
        averageValue: 415183667
