{
 "title": "Logstash on Kubernetes Dashboard",
 "description": "Logstash Health Monitoring: System, JVM, Pipeline and individual plugin stats for Logstash replicas running on Kubernetes.",
 "tags": [
  "logstash",
  "telemetry"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cpu_threshold", "label": "CPU Threshold", "query": "1.0" },
   { "name": "pod", "label": "Replica", "query": { "query": "query_result({app='logstash'})" } },
   {
    "name": "pipeline",
    "label": "Logstash Pipeline",
    "query": {
     "query": "query_result(logstash_stats_pipeline_events_in{pod=~'$pod'})"
    }
   },
   {
    "name": "input_plugin",
    "query": {
     "query": "query_result(logstash_stats_pipeline_plugin_events_out{pod=~'$pod',plugin_type='input'})"
    }
   },
   {
    "name": "filter_plugin",
    "query": {
     "query": "query_result(logstash_stats_pipeline_plugin_events_out{pod=~'$pod',plugin_type='filter'})"
    }
   },
   {
    "name": "output_plugin",
    "query": {
     "query": "query_result(logstash_stats_pipeline_plugin_events_out{pod=~'$pod',plugin_type='output'})"
    }
   },
   {
    "name": "plugin_type",
    "label": "Plugin Type",
    "query": {
     "query": "query_result(logstash_stats_pipeline_plugin_events_duration{pod=~'$pod'})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Events In/Out",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(logstash_stats_pipeline_events_in{pod=~'$pod',pipeline=~'$pipeline'}[$__range]))",
     "legendFormat": "IN"
    },
    {
     "expr": "sum(increase(logstash_stats_pipeline_events_out{pod=~'$pod',pipeline=~'$pipeline'}[$__range]))",
     "legendFormat": "OUT"
    }
   ]
  },
  {
   "title": "Pipeline Inputs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pipeline Input events / sec over the last hour ($pod)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(logstash_stats_pipeline_events_in{pod=~'$pod'}[$__range])",
     "legendFormat": "{{pipeline}}"
    },
    {
     "expr": "sum by (job) (irate(logstash_stats_pipeline_events_in{pod=~'$pod'}[$__range]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Input plugins: Queue Push Waiting Times ($pod)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(increase(logstash_stats_pipeline_plugin_events_queue_push_duration{pod=~'$pod',pipeline=~\"$pipeline\",plugin=~'$input_plugin',plugin_type='input'}[$__range])*1000/increase(logstash_stats_pipeline_plugin_events_out{pod=~'$pod',pipeline=~\"$pipeline\",plugin=~'$input_plugin',plugin_type='input'}[$__range])) by (pod, pipeline, plugin)",
     "legendFormat": "queue wait: ({{pipeline}}::{{plugin}})"
    }
   ]
  },
  {
   "title": "Pipeline Outputs ($pipeline)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "repeat": "pipeline",
   "targets": [
    {}
   ]
  },
  {
   "title": "Output events ($pod) ($output_plugin)",
   "type": "timeseries",
   "description": "An \"output event\" is a 20MB \"bulk\" send in most cases",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(logstash_stats_pipeline_plugin_events_out{pod=~'$pod',pipeline=~\"$pipeline\",plugin=~'$output_plugin',plugin_type='output'}[$__range])",
     "legendFormat": "{{pipeline}} ({{plugin}})"
    }
   ]
  },
  {
   "title": "Pipeline Output events / sec over the last hour ($pod)",
   "type": "timeseries",
   "description": "An \"output event\" is a 20MB \"bulk\" send in most cases",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(logstash_stats_pipeline_plugin_events_out{pod=~'$pod',plugin_type='output'}[$__range])",
     "legendFormat": "{{replica}} {{pipeline}}"
    },
    {
     "expr": "sum by (job) (irate(logstash_stats_pipeline_plugin_events_out{pod=~'$pod',plugin_type='output'}[$__range]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "JVM  (All Selected Replicas)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Old pool usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "logstash_stats_jvm_mem_pool_committed_bytes{pool='old',pod=~'$pod'}",
     "legendFormat": "old_pool_committed ({{pod}})"
    },
    {
     "expr": "logstash_stats_jvm_mem_pool_max_bytes{pool='old',pod=~'$pod'}",
     "legendFormat": "old_pool_max ({{pod}})"
    },
    {
     "expr": "logstash_stats_jvm_mem_pool_peak_max_bytes{pool='old',pod=~'$pod'}",
     "legendFormat": "old_pool_peak_max ({{pod}})"
    },
    {
     "expr": "logstash_stats_jvm_mem_pool_peak_used_bytes{pool='old',pod=~'$pod'}",
     "legendFormat": "old_pool_peak_used ({{pod}})"
    },
    {
     "expr": "logstash_stats_jvm_mem_pool_peak_used_bytes{pool='old',pod=~'$pod'}",
     "legendFormat": "old_used ({{pod}})"
    }
   ]
  },
  {
   "title": "Young pool usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "logstash_stats_jvm_mem_pool_committed_bytes{pool='young',pod=~'$pod'}",
     "legendFormat": "young_pool_committed ({{pod}})"
    },
    {
     "expr": "logstash_stats_jvm_mem_pool_max_bytes{pool='young',pod=~'$pod'}",
     "legendFormat": "young_pool_max  ({{pod}})"
    },
    {
     "expr": "logstash_stats_jvm_mem_pool_peak_max_bytes{pool='young',pod=~'$pod'}",
     "legendFormat": "young_pool_peak  ({{pod}})"
    },
    {
     "expr": "logstash_stats_jvm_mem_pool_peak_used_bytes{pool='young',pod=~'$pod'}",
     "legendFormat": "young_pool_peak_used ({{pod}})"
    },
    {
     "expr": "logstash_stats_jvm_mem_pool_peak_used_bytes{pool='young',pod=~'$pod'}",
     "legendFormat": "young_used ({{pod}})"
    }
   ]
  },
  {
   "title": "Survivor pool usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "logstash_stats_jvm_mem_pool_committed_bytes{pool='survivor',pod=~'$pod'}",
     "legendFormat": "{{pod}}-survivor_pool_committed"
    },
    {
     "expr": "logstash_stats_jvm_mem_pool_max_bytes{pool='survivor',pod=~'$pod'}",
     "legendFormat": "{{pod}}-survivor_pool_max"
    },
    {
     "expr": "logstash_stats_jvm_mem_pool_peak_max_bytes{pool='survivor',pod=~'$pod'}",
     "legendFormat": "{{pod}}-survivor_pool_peak_max"
    },
    {
     "expr": "logstash_stats_jvm_mem_pool_peak_used_bytes{pool='survivor',pod=~'$pod'}",
     "legendFormat": "{{pod}}-survivor_pool_peak_used"
    },
    {
     "expr": "logstash_stats_jvm_mem_pool_peak_used_bytes{pool='survivor',pod=~'$pod'}",
     "legendFormat": "{{pod}}-survivor_used"
    }
   ]
  },
  {
   "title": "JVM Heap % used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "logstash_stats_jvm_mem_heap_used_percent{pod=~'$pod'}",
     "legendFormat": "{{pod}}-jvm-usage"
    }
   ]
  },
  {
   "title": "JVM Heap usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "logstash_stats_jvm_mem_heap_max_bytes{pod=~'$pod'}",
     "legendFormat": "{{pod}}-jvm-max"
    },
    {
     "expr": "logstash_stats_jvm_mem_heap_used_bytes{pod=~'$pod'}",
     "legendFormat": "{{pod}}-jvm-used"
    }
   ]
  },
  {
   "title": "Threads count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "logstash_stats_jvm_threads_count{pod=~'$pod'}",
     "legendFormat": "{{pod}}-threads_count"
    },
    {
     "expr": "logstash_stats_jvm_threads_peak_count{pod=~'$pod'}",
     "legendFormat": "{{pod}}-threads_peak"
    }
   ]
  },
  {
   "title": "Pipeline I/O Health ($pipeline)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "repeat": "pipeline",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Processed Events I/O Rate ($pod)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "avg((irate(logstash_stats_pipeline_events_out{pod=~'$pod',pipeline=~\"$pipeline\"}[$__range])/irate(logstash_stats_pipeline_events_duration{pod=~'$pod',pipeline=~\"$pipeline\"}[$__range]))*1000) by (pod, pipeline)",
       "legendFormat": "Overall Rate (events/sec)"
      },
      {
       "expr": "avg((irate(logstash_stats_pipeline_queue_events_count{pod=~'$pod',pipeline=~\"$pipeline\",plugin_type='input'}[$__range])/irate(logstash_stats_pipeline_events_queue_push_duration{pod=~'$pod',pipeline=~\"$pipeline\",plugin_type='input'}[$__range]))*1000) by (pod, pipeline)",
       "legendFormat": "Input Queue Pressure (events/sec)"
      },
      {
       "expr": "avg((irate(logstash_stats_pipeline_plugin_events_out{pod=~'$pod',pipeline=~\"$pipeline\",plugin_type='output'}[$__range])/irate(logstash_stats_pipeline_plugin_events_duration{pod=~'$pod',pipeline=~\"$pipeline\",plugin_type='output'}[$__range])*1000) < 100000) by (pod, pipeline)",
       "legendFormat": "Outputs Rate (events/sec)"
      }
     ]
    }
   ]
  },
  {
   "title": "Pipeline Filters ($pipeline)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "repeat": "pipeline",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Processing Rate for Filters used in Pipeline $pipeline::$filter_plugin ($pod)",
     "type": "stat",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(logstash_stats_pipeline_plugin_events_in{pod=\"$pod\",pipeline=~\"$pipeline\",plugin=~\"$filter_plugin\",plugin_type='filter'}[$__range])/increase(logstash_stats_pipeline_plugin_events_duration{pod=\"$pod\",pipeline=~\"$pipeline\",plugin=~\"$filter_plugin\",plugin_type='filter'}[$__range])*1000) by (plugin, plugin_id)",
       "legendFormat": "{{plugin}} ({{plugin_id}})"
      }
     ]
    }
   ]
  }
 ]
}